### PR TITLE
Form elements are now registered

### PR DESCRIPTION
**Pull request by derrell**
Each form element provides its own set of handlers. The internally-provided form elements are now each implemented in their own (static) class, and they get registered automatically. User code can implement handlers for its own IForm-respecting form elements.

### CODE REVIEW

**Review by cboulanger — APPROVED** [review]
Absolutely fantastic! This is exactly what I meant when I was talking about self-documenting code. This turns the form builder from a black box to an extensible toolbox with an API. Thank you!!

**Comment by cboulanger** [comment]
Maybe we're turning this into an incubator eventually 😄 !

**Comment by oetiker** [comment]
a form inside a dialog ... sounds like a tail waggling with its dog ... shouldn't the window around this be sort of optional :)

**Comment by derrell** [comment]
Exactly! The window is now optional. If you use `qxl.dialog.Form` you get the traditional windowed form. If you use `qxl.dialog.FormEmbed` you instead get a container that you can place wherever you like it.

But that was a prior PR, from a couple of days ago. This one just allows the pre-existing functionality of a form (whether in a window or a container) to be easily extended by user-registered form elements.

**Comment by cboulanger** [comment]
@oetiker Even a "Prompt" dialog is nothing more than a one-field form in a window.... 😄  and you see a lot of forms in the Dialog package demo: http://qooxdoo.org/qxl.dialog/  --- so nothing new here. 

But it's great @derrell factored out the logic so that the form can be used outside of popup windows, and, more importantly, that they are now extensible and configurable. The form builder should really be its own package, but the current state of tight integration with the other dialogs is how it has historically evolved.

**Pull request merged**
